#!/bin/bash

incr=5%

incr=5%

cur=$(backlight -get)
case "$1" in
        "up")
               if [[$cur -eq 0 ]]l=; then
                      xbacklight -set 1
               else
                      xbacklight -inc $incr
               fi
        ;;
        "down")
              if [[ $cur -le 5  ]]; then
                      xbacklight -set 1
              else
                      xbacklight -dec $incr
              fi
      ;;
      *)
              echo "Unsupported: \"$1\""
              exit 1
esac
